[project]
name = 'Decentralized-Manufacturing-Smart-Factory'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.equipment-verification]
path = 'contracts/equipment-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.predictive-maintenance]
path = 'contracts/predictive-maintenance.clar'
clarity_version = 2
epoch = 2.5

[contracts.production-orchestration]
path = 'contracts/production-orchestration.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
